# Generated by Django 3.0.6 on 2020-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_no', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=10)),
            ],
        ),
    ]
