# Generated by Django 3.0.6 on 2020-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='POLL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Myquestion',
        ),
        migrations.DeleteModel(
            name='Userresult',
        ),
    ]
